# **NumPy Array**

Existen 6 mecanismos generales para crear Arrays:

1. Conversión desde otras estructuras de Python (por ejemplo, listas y tuplas)
2. Funciones intrínsecas de NumPy para la creación de arrays (por ejemplo, arange, ones, zeros, etc.)
3. Replicación, unión o mutación de matrices existentes
4. Lectura de matrices desde disco, ya sea desde formatos estándar o personalizados
5. Creación de matrices a partir de bytes sin procesar mediante cadenas o buffers.
6. Utilización de funciones especiales de biblioteca (por ejemplo, random)

Puede utilizar estos métodos para crear ndarrays o arrays estructurados.

In [1]:
import numpy as np

## 1. Conversión desde otras estructuras de Python (por ejemplo, listas y tuplas)

Los Array de NumPy pueden definirse utilizando secuencias de Python como listas y tuplas. Las listas y tuplas se definen utilizando [...] y (...), respectivamente. Las listas y tuplas pueden definir la creación de ndarray:

- una lista de números creará un Array 1D
- una lista de listas creará un Array 2D
- otras listas anidadas crearán matrices de mayor dimensión. En general, cualquier objeto array se denomina ndarray en NumPy.

In [5]:
lista = [1,2,3,4,5,6,7,8]
arr = np.array(lista)
type(arr)

numpy.ndarray

In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
type(matriz)

numpy.ndarray

## 2. Funciones intrínsecas de NumPy para la creación de arrays

NumPy tiene más de 40 funciones incorporadas para crear arrays, como se indica en [las rutinas de creación de arrays](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation). Estas funciones pueden dividirse en aproximadamente tres categorías, basadas en la dimensión del array que crean:

- Matrices 1D
- matrices 2D
- ndarrays

### Funciones de creación de arrays 1D

Las funciones de creación de arrays 1D, por ejemplo `numpy.linspace` y `numpy.arange`, generalmente necesitan al menos dos entradas, `start` y `stop`.

`numpy.arange` crea arrays con valores que se incrementan regularmente.

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

`numpy.linspace` creará arrays con un número especificado de elementos, y espaciados equitativamente entre los valores especificados de inicio y final.
La ventaja de esta función de creación es que garantiza el número de elementos y el punto inicial y final. El arange(inicio, parada, paso) anterior no incluirá el valor parada.

In [7]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Funciones de creación de arrays 2D
Las funciones de creación de arrays 2D, por ejemplo numpy.eye, numpy.diag y numpy.vander, definen propiedades de matrices especiales representadas como arrays 2D.

`np.eye(n, m)` define un array 2D. Los elementos donde i=j (índice de fila e índice de columna son iguales) son 1 y el resto son 0, como tal:

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

`numpy.diag` puede definir un array cuadrado 2D con valores dados a lo largo de la diagonal o, si se le da un array  2D, devuelve un arreglo 1D que contiene sólo los elementos diagonales. Las dos funciones de creación de arreglos pueden ser útiles cuando se hace álgebra lineal:

In [10]:
np.diag([1, 2, 3])


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [12]:
np.diag([1, 2, 3], 2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

`vander(x, n)` define un array de Vandermonde como una matriz 2D NumPy. Cada columna del array Vandermonde es una potencia decreciente del array 1D de entrada o lista o tupla, x donde el orden polinómico más alto es n-1. Esta rutina de creación de matrices es útil para generar modelos lineales de mínimos cuadrados, como tal:

In [14]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [15]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [16]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

### Indexing

In [27]:
arr[5] + arr[0]

7

In [28]:
matriz[0]


array([1, 2, 3])

In [29]:
matriz[0,1]

2

### Slicing

In [30]:
arr[3:7]

array([4, 5, 6, 7])

In [31]:
arr[:3]

array([1, 2, 3])

In [32]:
arr[5:]

array([6, 7, 8])

In [33]:
arr[::3]

array([1, 4, 7])

In [34]:
arr[-1]

8

In [35]:
arr[-5]

4

In [36]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])