In [23]:
import numpy as np

### Creando listas

In [24]:
lista = [1,2,3,4,5,6,7,8]
lista

[1, 2, 3, 4, 5, 6, 7, 8]

### Creando array

In [25]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [26]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indexing

In [27]:
arr[5] + arr[0]

7

In [28]:
matriz[0]


array([1, 2, 3])

In [29]:
matriz[0,1]

2

### Slicing

In [30]:
arr[3:7]

array([4, 5, 6, 7])

In [31]:
arr[:3]

array([1, 2, 3])

In [32]:
arr[5:]

array([6, 7, 8])

In [33]:
arr[::3]

array([1, 4, 7])

In [34]:
arr[-1]

8

In [35]:
arr[-5]

4

In [36]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])