# **NumPy Array**

Existen 6 mecanismos generales para crear Arrays:

- Conversión desde otras estructuras de Python (por ejemplo, listas y tuplas)
- Funciones intrínsecas de NumPy para la creación de arrays (por ejemplo, arange, ones, zeros, etc.)
- Replicación, unión o mutación de matrices existentes
- Lectura de matrices desde disco, ya sea desde formatos estándar o personalizados
- Creación de matrices a partir de bytes sin procesar mediante cadenas o buffers.
- Utilización de funciones especiales de biblioteca (por ejemplo, random)

Puede utilizar estos métodos para crear ndarrays o arrays estructurados.

In [1]:
import numpy as np

## Conversión desde otras estructuras de Python (por ejemplo, listas y tuplas)

Los Array de NumPy pueden definirse utilizando secuencias de Python como listas y tuplas. Las listas y tuplas se definen utilizando [...] y (...), respectivamente. Las listas y tuplas pueden definir la creación de ndarray:

- una lista de números creará un Array 1D,
- una lista de listas creará un Array 2D,

otras listas anidadas crearán matrices de mayor dimensión. En general, cualquier objeto array se denomina ndarray en NumPy.

In [24]:
lista = [1,2,3,4,5,6,7,8]
lista

[1, 2, 3, 4, 5, 6, 7, 8]

In [25]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [26]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indexing

In [27]:
arr[5] + arr[0]

7

In [28]:
matriz[0]


array([1, 2, 3])

In [29]:
matriz[0,1]

2

### Slicing

In [30]:
arr[3:7]

array([4, 5, 6, 7])

In [31]:
arr[:3]

array([1, 2, 3])

In [32]:
arr[5:]

array([6, 7, 8])

In [33]:
arr[::3]

array([1, 4, 7])

In [34]:
arr[-1]

8

In [35]:
arr[-5]

4

In [36]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])