# **Tipos de datos**

NumPy soporta una variedad mucho mayor de tipos numéricos que Python.


In [10]:
import numpy as np

Para determinar el tipo de una matriz, mira el atributo dtype:

In [11]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

### Cambiando tipos de datos

In [12]:
arr = np.array([1,2,3], dtype='float64')
arr.dtype

dtype('float64')

In [13]:
arr

array([1., 2., 3.])

In [14]:
arr = arr.astype(np.float64)
arr.dtype

dtype('float64')

In [15]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [16]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [17]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)