In [1]:
import numpy as np

In [8]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.random.rand()


array([[0.76347132, 0.28324787, 0.74837644, 0.48378565],
       [0.16159225, 0.46071676, 0.9812417 , 0.21636671],
       [0.03811392, 0.84510154, 0.26271256, 0.65989129],
       [0.60158612, 0.85574412, 0.09753177, 0.95876925]])

In [18]:
np.random.rand(4)

array([0.89938486, 0.18966976, 0.68184577, 0.4040073 ])

In [19]:

np.random.rand(4,4)

array([[0.51380849, 0.45910294, 0.53903212, 0.68695619],
       [0.72871449, 0.14497046, 0.31399278, 0.71827395],
       [0.45315704, 0.65339415, 0.07081593, 0.68637787],
       [0.89594585, 0.83790462, 0.59227262, 0.92037535]])

In [23]:
np.random.randint(1,11)

10

In [24]:
np.random.randint(1,100,(10,10))

array([[78, 87, 28, 50, 77, 65, 64, 13, 47, 74],
       [56, 30, 71, 77, 30, 13, 79, 43, 53, 10],
       [92, 83, 13, 96, 97, 33, 57,  7, 80, 70],
       [22, 15, 62,  4, 67, 48, 35, 49,  7, 98],
       [14, 17, 76, 28, 14, 58, 94, 20, 99, 35],
       [79,  5, 96, 21, 90, 48, 31, 67, 50, 40],
       [76,  4, 74, 82, 46, 97, 73, 67, 23, 10],
       [45,  2, 31, 20, 75, 72, 65, 11, 30, 41],
       [ 7, 62, 84, 62, 91, 30, 41, 91, 38, 75],
       [51, 35, 16, 46, 89, 78, 10, 75, 15, 51]])