In [1]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand()


array([[0.76347132, 0.28324787, 0.74837644, 0.48378565],
       [0.16159225, 0.46071676, 0.9812417 , 0.21636671],
       [0.03811392, 0.84510154, 0.26271256, 0.65989129],
       [0.60158612, 0.85574412, 0.09753177, 0.95876925]])

In [18]:
np.random.rand(4)

array([0.89938486, 0.18966976, 0.68184577, 0.4040073 ])

In [19]:

np.random.rand(4,4)

array([[0.51380849, 0.45910294, 0.53903212, 0.68695619],
       [0.72871449, 0.14497046, 0.31399278, 0.71827395],
       [0.45315704, 0.65339415, 0.07081593, 0.68637787],
       [0.89594585, 0.83790462, 0.59227262, 0.92037535]])

In [23]:
np.random.randint(1,11)

10

In [24]:
np.random.randint(1,100,(10,10))

array([[78, 87, 28, 50, 77, 65, 64, 13, 47, 74],
       [56, 30, 71, 77, 30, 13, 79, 43, 53, 10],
       [92, 83, 13, 96, 97, 33, 57,  7, 80, 70],
       [22, 15, 62,  4, 67, 48, 35, 49,  7, 98],
       [14, 17, 76, 28, 14, 58, 94, 20, 99, 35],
       [79,  5, 96, 21, 90, 48, 31, 67, 50, 40],
       [76,  4, 74, 82, 46, 97, 73, 67, 23, 10],
       [45,  2, 31, 20, 75, 72, 65, 11, 30, 41],
       [ 7, 62, 84, 62, 91, 30, 41, 91, 38, 75],
       [51, 35, 16, 46, 89, 78, 10, 75, 15, 51]])