In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape

(3, 2)

In [5]:
arr

array([[2, 3],
       [9, 8],
       [1, 4]])

In [6]:
arr.reshape(1,6)

array([[2, 3, 9, 8, 1, 4]])

In [7]:
arr.reshape(2,3)

array([[2, 3, 9],
       [8, 1, 4]])

In [8]:
np.reshape(arr,(1,6))

array([[2, 3, 9, 8, 1, 4]])

In [9]:
arr

array([[2, 3],
       [9, 8],
       [1, 4]])

In [10]:
np.reshape(arr,(2,3),'C')

array([[2, 3, 9],
       [8, 1, 4]])

In [11]:
np.reshape(arr,(2,3),'F')

array([[2, 1, 8],
       [9, 3, 4]])

In [12]:
np.reshape(arr,(2,3),'A')

array([[2, 3, 9],
       [8, 1, 4]])