In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)
matriz = arr.reshape(2,5)

In [3]:
print("matriz")
print(matriz)
print("array")
print(arr)

matriz
[[16  5 17 13  1]
 [14  3 16 13 19]]
array
[16  5 17 13  1 14  3 16 13 19]


# MAX

Para obtener el valor maximo

In [4]:
print("arr.max() ", arr.max())
print("matriz.max() ", matriz.max())

arr.max()  19
matriz.max()  19


En una matriz podemos obtener el valor maximo de cada array por eje

In [5]:
print("matriz.max(0) ", matriz.max(0))
print("matriz.max(1) ", matriz.max(1))

matriz.max(0)  [16  5 17 13 19]
matriz.max(1)  [17 19]


# ARGMAX

Para obtener el index del valor mas grande

In [6]:
print("arr.argmax() ", arr.argmax())
print("matriz.argmax() ", matriz.argmax())

arr.argmax()  9
matriz.argmax()  9


# MIN

Devuelve el valor mas pequeño del array

In [7]:
print("arr.min() ", arr.min())
print("matriz.min() ", matriz.min())

arr.min()  1
matriz.min()  1


# ARGMIN

Devuelve el index del valor mas pequeño

In [8]:
print("arr.argmin() ", arr.argmin())
print("matriz.argmin() ", matriz.argmin())

arr.argmin()  4
matriz.argmin()  4


PTP

De un pico a otro pico
Devuelve la diferencia entre el valor mas pequeño y el valor mas grande

In [9]:
print("arr")
print(arr)
print("min",arr.min())
print("max", arr.max())
print("arr.ptp", arr.ptp())

arr
[16  5 17 13  1 14  3 16 13 19]
min 1
max 19
arr.ptp 18


In [10]:
print("matriz")
print(matriz)
print("min",matriz.min())
print("max", matriz.max())
print("matriz.ptp", matriz.ptp())

matriz
[[16  5 17 13  1]
 [14  3 16 13 19]]
min 1
max 19
matriz.ptp 18


# Percentile



In [11]:
print(arr)

print("percentile")
np.percentile(arr,50)

[16  5 17 13  1 14  3 16 13 19]
percentile


13.5

# Sort

In [13]:
arr.sort()
arr

array([ 1,  3,  5, 13, 13, 14, 16, 16, 17, 19])

# Median

In [14]:
np.median(arr)

13.5

In [15]:
np.median(matriz,0)

array([ 7.5,  9.5, 10.5, 15. , 16. ])

# STD

In [16]:
np.std(arr)

6.017474553332153

In [17]:
np.std(arr) ** 2

36.21

# Var

In [18]:
np.var(arr)

36.21

# Mean

In [19]:
np.mean(arr)

11.7

# Concanate

In [22]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [24]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a.ndim
b.ndim

2

In [25]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [26]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])