In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [6]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
1 / arr[arr > 0]

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
matriz2 = matriz.copy()

In [17]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [18]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [20]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [21]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])