In [1]:
import sys
import numpy as np

In [2]:
array_id = np.array([4.5, 3])
type(array_id)

numpy.ndarray

In [3]:
array_id.ndim

1

In [4]:
array_id.shape

(2,)

In [5]:
matriz = np.array([
    [1,2,3],
    [4,5,6]
])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
matriz.ndim

2

In [7]:
matriz.shape

(2, 3)

In [8]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones((2))

array([1., 1.])

In [10]:
np.random.random((2,3))

array([[0.56254796, 0.34782696, 0.09281269],
       [0.41970856, 0.97676236, 0.49627231]])

In [19]:
#!cat np_text.txt
#type np_text.txt

In [18]:
#np_text = np.genfromtxt('np_text.txt', delimiter=',')
#np_text

In [13]:
lista_2d = [[1,2,3], [4,5,6]]
array_2d = np.array([[1,2,3], [4,5,6]])

In [14]:
sys.getsizeof(lista_2d)
sys.getsizeof(array_2d)

152

In [15]:
sys.getsizeof(array_2d)

152

In [16]:
sys.getsizeof(lista_2d)

72

In [18]:
%%timeit

sum(range(1000000))

87 ms ± 3.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%%timeit

np.sum(np.arange(1000000))

4.29 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
